apiVersion: apps/v1
kind: Deployment
metadata:
  name: darwaza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darwaza
  template:
    metadata:
      labels:
        app: darwaza
    spec:
      containers:
        - name: darwaza
          image: darwaza:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PEHCHAN_URL
              value: http://pehchan:8081
            - name: POKEMON_URL
              value: http://pokemon:8082
            - name: DBZ_URL
              value: http://dbz:8083
---
apiVersion: v1
kind: Service
metadata:
  name: darwaza
spec:
  type: ClusterIP
  selector:
    app: darwaza
  ports:
    - port: 8080
      targetPort: 8080
