apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbz
  template:
    metadata:
      labels:
        app: dbz
    spec:
      containers:
        - name: dbz
          image: dbz:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: dbz
spec:
  selector:
    app: dbz
  ports:
    - port: 8083
      targetPort: 8083
