apiVersion: apps/v1
kind: Deployment
metadata:
  name: pehchan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pehchan
  template:
    metadata:
      labels:
        app: pehchan
    spec:
      containers:
        - name: pehchan
          image: pehchan:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pehchan
spec:
  selector:
    app: pehchan
  ports:
    - port: 8081
      targetPort: 8081
