apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: service1:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE2_URL
              value: "http://service2:8081/process"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
